# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lidar_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lidar_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lidar_stream.proto\x12\x05lidar\"\x97\x01\n\rLaserScanData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x11\n\trange_min\x18\x05 \x01(\x02\x12\x11\n\trange_max\x18\x06 \x01(\x02\x12\x0e\n\x06ranges\x18\x07 \x03(\x02\"\x0f\n\rStreamRequest2J\n\x0cLidarService\x12:\n\nStreamScan\x12\x14.lidar.StreamRequest\x1a\x14.lidar.LaserScanData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lidar_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LASERSCANDATA']._serialized_start=30
  _globals['_LASERSCANDATA']._serialized_end=181
  _globals['_STREAMREQUEST']._serialized_start=183
  _globals['_STREAMREQUEST']._serialized_end=198
  _globals['_LIDARSERVICE']._serialized_start=200
  _globals['_LIDARSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
