# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception_udp.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'perception_udp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14perception_udp.proto\x12\x0eperception_udp\"\x97\x01\n\nScanPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x11\n\trange_min\x18\x05 \x01(\x02\x12\x11\n\trange_max\x18\x06 \x01(\x02\x12\x11\n\tranges_mm\x18\x07 \x01(\x0c\"i\n\nOdomSample\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\n\n\x02qz\x18\x04 \x01(\x01\x12\n\n\x02qw\x18\x05 \x01(\x01\x12\n\n\x02vx\x18\x06 \x01(\x01\x12\x0e\n\x06vtheta\x18\x07 \x01(\x01\"9\n\nOdomPacket\x12+\n\x07samples\x18\x01 \x03(\x0b\x32\x1a.perception_udp.OdomSample\"b\n\x0bHelloPacket\x12\x12\n\nrobot_name\x18\x01 \x01(\t\x12\x11\n\tscan_bins\x18\x02 \x01(\r\x12\x14\n\x0cscan_rate_hz\x18\x03 \x01(\x01\x12\x16\n\x0elaser_frame_id\x18\x04 \x01(\t\"$\n\x0fHeartbeatPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\"\xc3\x01\n\x0bStatsPacket\x12\x16\n\x0escans_received\x18\x01 \x01(\x04\x12\x12\n\nscans_lost\x18\x02 \x01(\x04\x12\x17\n\x0fscans_reordered\x18\x03 \x01(\x04\x12\x12\n\nloss_ratio\x18\x04 \x01(\x01\x12\x11\n\tjitter_ms\x18\x05 \x01(\x01\x12\x15\n\rinference_fps\x18\x06 \x01(\x01\x12\x15\n\ractive_tracks\x18\x07 \x01(\r\x12\x1a\n\x12scans_dropped_busy\x18\x08 \x01(\x04\"\x1b\n\tByePacket\x12\x0e\n\x06reason\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_udp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANPACKET']._serialized_start=41
  _globals['_SCANPACKET']._serialized_end=192
  _globals['_ODOMSAMPLE']._serialized_start=194
  _globals['_ODOMSAMPLE']._serialized_end=299
  _globals['_ODOMPACKET']._serialized_start=301
  _globals['_ODOMPACKET']._serialized_end=358
  _globals['_HELLOPACKET']._serialized_start=360
  _globals['_HELLOPACKET']._serialized_end=458
  _globals['_HEARTBEATPACKET']._serialized_start=460
  _globals['_HEARTBEATPACKET']._serialized_end=496
  _globals['_STATSPACKET']._serialized_start=499
  _globals['_STATSPACKET']._serialized_end=694
  _globals['_BYEPACKET']._serialized_start=696
  _globals['_BYEPACKET']._serialized_end=723
# @@protoc_insertion_point(module_scope)
