# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lidar_stream_pb2 as lidar__stream__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lidar_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LidarServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamScan = channel.unary_stream(
                '/lidar.LidarService/StreamScan',
                request_serializer=lidar__stream__pb2.StreamRequest.SerializeToString,
                response_deserializer=lidar__stream__pb2.LaserScanData.FromString,
                _registered_method=True)


class LidarServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamScan(self, request, context):
        """Server-streaming RPC: RPi streams LiDAR scans continuously to Jetson Nano
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LidarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamScan': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScan,
                    request_deserializer=lidar__stream__pb2.StreamRequest.FromString,
                    response_serializer=lidar__stream__pb2.LaserScanData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lidar.LidarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lidar.LidarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LidarService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lidar.LidarService/StreamScan',
            lidar__stream__pb2.StreamRequest.SerializeToString,
            lidar__stream__pb2.LaserScanData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
