# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import odom_stream_pb2 as odom__stream__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in odom_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OdometryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamOdometry = channel.unary_stream(
                '/odom.OdometryService/StreamOdometry',
                request_serializer=odom__stream__pb2.StreamRequest.SerializeToString,
                response_deserializer=odom__stream__pb2.OdometryData.FromString,
                _registered_method=True)


class OdometryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamOdometry(self, request, context):
        """Server-streaming, same direction/shape as LidarService.StreamScan: the robot
        serves, the consumer dials in and pulls for as long as it keeps the call open.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OdometryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamOdometry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOdometry,
                    request_deserializer=odom__stream__pb2.StreamRequest.FromString,
                    response_serializer=odom__stream__pb2.OdometryData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'odom.OdometryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('odom.OdometryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OdometryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamOdometry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/odom.OdometryService/StreamOdometry',
            odom__stream__pb2.StreamRequest.SerializeToString,
            odom__stream__pb2.OdometryData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
