# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: track_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'track_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12track_stream.proto\x12\x05track\"q\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\x12\r\n\x05speed\x18\x06 \x01(\x02\x12\x0f\n\x07heading\x18\x07 \x01(\x02\x12\x0e\n\x06moving\x18\x08 \x01(\x08\"O\n\nTrackArray\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1c\n\x06tracks\x18\x03 \x03(\x0b\x32\x0c.track.Track\"\"\n\x07PushAck\x12\x17\n\x0ftracks_received\x18\x01 \x01(\x05\x32\x41\n\x0cTrackService\x12\x31\n\nPushTracks\x12\x11.track.TrackArray\x1a\x0e.track.PushAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'track_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACK']._serialized_start=29
  _globals['_TRACK']._serialized_end=142
  _globals['_TRACKARRAY']._serialized_start=144
  _globals['_TRACKARRAY']._serialized_end=223
  _globals['_PUSHACK']._serialized_start=225
  _globals['_PUSHACK']._serialized_end=259
  _globals['_TRACKSERVICE']._serialized_start=261
  _globals['_TRACKSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
