# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import track_stream_pb2 as track__stream__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in track_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushTracks = channel.stream_unary(
                '/track.TrackService/PushTracks',
                request_serializer=track__stream__pb2.TrackArray.SerializeToString,
                response_deserializer=track__stream__pb2.PushAck.FromString,
                _registered_method=True)


class TrackServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PushTracks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushTracks': grpc.stream_unary_rpc_method_handler(
                    servicer.PushTracks,
                    request_deserializer=track__stream__pb2.TrackArray.FromString,
                    response_serializer=track__stream__pb2.PushAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'track.TrackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('track.TrackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushTracks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/track.TrackService/PushTracks',
            track__stream__pb2.TrackArray.SerializeToString,
            track__stream__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
