# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracked_people.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tracked_people.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tracked_people.proto\x12\x0etracked_people\"\x82\x01\n\rTrackedPerson\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\x12\x10\n\x08\x66uture_x\x18\x06 \x01(\x02\x12\x10\n\x08\x66uture_y\x18\x07 \x01(\x02\x12\r\n\x05speed\x18\x08 \x01(\x02\"V\n\x12TrackedPeopleFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12-\n\x06people\x18\x02 \x03(\x0b\x32\x1d.tracked_people.TrackedPerson\"\x11\n\x0fTrackingRequest2t\n\x14TrackedPeopleService\x12\\\n\x13StreamTrackedPeople\x12\x1f.tracked_people.TrackingRequest\x1a\".tracked_people.TrackedPeopleFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracked_people_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKEDPERSON']._serialized_start=41
  _globals['_TRACKEDPERSON']._serialized_end=171
  _globals['_TRACKEDPEOPLEFRAME']._serialized_start=173
  _globals['_TRACKEDPEOPLEFRAME']._serialized_end=259
  _globals['_TRACKINGREQUEST']._serialized_start=261
  _globals['_TRACKINGREQUEST']._serialized_end=278
  _globals['_TRACKEDPEOPLESERVICE']._serialized_start=280
  _globals['_TRACKEDPEOPLESERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
