# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'perception_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17perception_stream.proto\x12\nperception\"\x97\x01\n\rLaserScanData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x11\n\trange_min\x18\x05 \x01(\x02\x12\x11\n\trange_max\x18\x06 \x01(\x02\x12\x0e\n\x06ranges\x18\x07 \x03(\x02\"k\n\x0cOdometryData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\n\n\x02qz\x18\x04 \x01(\x01\x12\n\n\x02qw\x18\x05 \x01(\x01\x12\n\n\x02vx\x18\x06 \x01(\x01\x12\x0e\n\x06vtheta\x18\x07 \x01(\x01\"m\n\x0bSensorFrame\x12)\n\x04scan\x18\x01 \x01(\x0b\x32\x19.perception.LaserScanDataH\x00\x12(\n\x04odom\x18\x02 \x01(\x0b\x32\x18.perception.OdometryDataH\x00\x42\t\n\x07payload\"$\n\tSensorAck\x12\x17\n\x0fscans_processed\x18\x01 \x01(\x05\x32Y\n\x11PerceptionService\x12\x44\n\x10StreamSensorData\x12\x17.perception.SensorFrame\x1a\x15.perception.SensorAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LASERSCANDATA']._serialized_start=40
  _globals['_LASERSCANDATA']._serialized_end=191
  _globals['_ODOMETRYDATA']._serialized_start=193
  _globals['_ODOMETRYDATA']._serialized_end=300
  _globals['_SENSORFRAME']._serialized_start=302
  _globals['_SENSORFRAME']._serialized_end=411
  _globals['_SENSORACK']._serialized_start=413
  _globals['_SENSORACK']._serialized_end=449
  _globals['_PERCEPTIONSERVICE']._serialized_start=451
  _globals['_PERCEPTIONSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
